# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ef53d9b64caef5bc0f6eb81ad223315a"
name = "uship-dynamic-checkout-pricing"
handle = "uship-dynamic-checkout-pricing"
application_url = "https://example.com/"
embedded = true

[build]
dev_store_url = "baker-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "unstable"

[pos]
embedded = false
